### ISSUE TITLE
[BUG]: Logo flipped in RTL Layout

### ISSUE THREAD

**Issue by CPKreu** [PixiEditor/PixiEditor#1172]
### Bug Description

The PixiEditor Logo is flipped in the Right to Left Layout

<img width="566" height="222" alt="Image" src="https://github.com/user-attachments/assets/db71295a-29cd-4744-8dc1-4b162008c6a7" />

### Steps how to trigger the issue

```bash
Select a RTL Language or use the Localization Debug Window to force other flow direction
```

### How did you download the software?

Built from source

### Version Channel

Development

### Version Number

2.0.1.11

### Operating System

Windows

### OS Version

Windows 11

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by flabbet** [comment]
Fixed in 2.0.1.13-dev

**Comment by Norange01** [comment]
@flabbet Still a problem for "Hello there!" window central logo. I can fix it if you don't want to

<img width="1335" height="1080" alt="Image" src="https://github.com/user-attachments/assets/1e039938-3886-425e-8965-21a9790c4798" />
